# Generated by Django 5.0.4 on 2024-04-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citytranslation',
            name='name',
            field=models.CharField(default=1, max_length=64, verbose_name='название'),
            preserve_default=False,
        ),
    ]
