# Generated by Django 5.0.4 on 2024-04-13 23:23

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0002_alter_citytranslation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(max_length=10, verbose_name='цвет')),
                ('icon', models.ImageField(upload_to='', verbose_name='икона')),
                ('icon_svg', models.ImageField(upload_to='', verbose_name='икона svg')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.ImageField(upload_to='', verbose_name='икона')),
            ],
            options={
                'verbose_name': 'Пропертй',
                'verbose_name_plural': 'Пропертй',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=250, null=True, verbose_name='адрес')),
                ('short_description', models.CharField(max_length=300, verbose_name='краткое описание')),
                ('description', models.TextField(verbose_name='описание')),
                ('opening_hours', models.CharField(blank=True, max_length=250, null=True, verbose_name='часы работы')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Веб-сайт')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='телеграм')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Фейсбук')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='инстаграм')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Твиттер')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='YouTube')),
                ('phone_number', models.CharField(blank=True, null=True, verbose_name='номер телефона')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='расположение')),
                ('show_in_map', models.BooleanField(verbose_name='показать на карте? ')),
                ('is_main', models.BooleanField(verbose_name='основной')),
                ('is_published', models.BooleanField(verbose_name='опубликовано')),
                ('stars', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='звезды')),
                ('panorama', models.ImageField(blank=True, null=True, upload_to='', verbose_name='панорама')),
                ('video', models.FileField(blank=True, null=True, upload_to='', verbose_name='видео')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='', verbose_name='обложка')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='логотип')),
                ('audio', models.FileField(blank=True, null=True, upload_to='', verbose_name='аудио')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='place.category', verbose_name='категория')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='city.city', verbose_name='город')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='place.place')),
            ],
            options={
                'verbose_name': 'место',
                'verbose_name_plural': 'места',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PlaceProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(verbose_name='валуе')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='place.place', verbose_name='')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='place.property')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='place.category')),
            ],
            options={
                'verbose_name': 'категория Translation',
                'db_table': 'place_category_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PlaceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='place.place')),
            ],
            options={
                'verbose_name': 'место Translation',
                'db_table': 'place_place_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PropertyTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='place.property')),
            ],
            options={
                'verbose_name': 'Пропертй Translation',
                'db_table': 'place_property_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
