# Generated by Django 5.0.4 on 2024-04-14 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_place_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='place',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='place.place', verbose_name='родитель'),
        ),
    ]
