# Generated by Django 5.0.4 on 2024-04-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_remove_place_phone_number_alter_place_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='номер телефона'),
        ),
    ]
