# Generated by Django 5.0.4 on 2024-04-14 01:31

import apps.place.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_alter_place_panorama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='panorama',
            field=models.ImageField(blank=True, null=True, upload_to=apps.place.models.upload_panorama, verbose_name='панорама'),
        ),
    ]
