# Generated by Django 5.0.4 on 2024-04-14 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_place_old_panorama_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='old_panorama_name',
        ),
    ]
