# Generated by Django 5.0.4 on 2024-04-14 07:35

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0009_remove_place_old_panorama_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(upload_to=apps.core.utils.upload_media_path, verbose_name='икона'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_svg',
            field=models.ImageField(upload_to=apps.core.utils.upload_media_path, verbose_name='икона svg'),
        ),
        migrations.AlterField(
            model_name='place',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=apps.core.utils.upload_media_path, verbose_name='аудио'),
        ),
        migrations.AlterField(
            model_name='place',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.utils.upload_media_path, verbose_name='логотип'),
        ),
        migrations.AlterField(
            model_name='place',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.utils.upload_media_path, verbose_name='обложка'),
        ),
        migrations.AlterField(
            model_name='place',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=apps.core.utils.upload_media_path, verbose_name='видео'),
        ),
        migrations.AlterField(
            model_name='property',
            name='icon',
            field=models.ImageField(upload_to=apps.core.utils.upload_media_path, verbose_name='икона'),
        ),
    ]
