# Generated by Django 5.0.4 on 2024-04-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0010_alter_category_icon_alter_category_icon_svg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
